### ISSUE TITLE
[Discussion] Use markdown for authoring

### ISSUE THREAD

**Issue by DexterPOSH** [AzureTalk/Script#1]
Hi everyone,

I see that the files pushed to the repository are not using markdown.
Can we standardize on that?

**Comment by ashishrajsrivastava** [comment]
seems like a good idea, i would add one more thing to have each script in a separate folder with relevant name and have markdown in that folder for that script or tool.

**Comment by DexterPOSH** [comment]
Closing this now, since this is already a work in progress.
